[build]
target = "thumbv6m-none-eabi"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
#runner = "probe-run --chip ATSAMD21G18A"
#runner = 'arm-none-eabi-gdb -q -x bmp.gdb'
runner = 'arm-none-eabi-gdb -q -x openocd.gdb'

[target.thumbv6m-none-eabi]
rustflags = [ "-C", "link-arg=-Tlink.x", ]
